repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      # Lint files
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # Prevent adding private keys in files
      - id: detect-private-key
      # Detect problematic referenced files
      - id: check-symlinks
