name: Build and Push Version

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - ready_for_review
      - assigned
    paths:
      - "image_version.txt"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    -   name: Checkout code
        uses: actions/checkout@v4
    
    - name: Read the image version
      id: image_version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./image_version.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            pranavmishra90/ansible:latest
            pranavmishra90/ansible:${{ steps.image_version.outputs.content }}

          
          # ghcr.io/pranavmishra90/ansible:latest
          # ghcr.io/pranavmishra90/ansible:${{ steps.image_version.outputs.content }}           

      - name: Write to workflow job summary
        run: |
          build_version=$(cat ./image_version.txt)
          builder_header="# $build_version "
          echo "$builder_header" > job_summary.md

          echo "   " >> job_summary.md
          echo "Completed build of [pranavmishra90/ansible](https://hub.docker.com/r/pranavmishra90/ansible)" >> job_summary.md
          cat job_summary.md >> $GITHUB_STEP_SUMMARY